/**
 * Email templates as inline HTML strings. No template engine to keep things simple.
 * Templates use the maison's serif typography, deep purple brand color, and gold rule.
 */
import { formatBdt } from "@/lib/utils";

const SHELL = (body: string) => `<!doctype html>
<html><head><meta charset="utf-8"/><title>Saanguine Maison</title></head>
<body style="margin:0;padding:0;background:#fdfbf7;font-family:Georgia,'Cormorant Garamond',serif;color:#2a1854;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#fdfbf7;padding:40px 20px;">
    <tr><td align="center">
      <table role="presentation" width="560" cellspacing="0" cellpadding="0" border="0" style="background:white;max-width:560px;width:100%;">
        <tr><td style="padding:40px 40px 20px;border-bottom:1px solid #e8e0d2;text-align:center;">
          <div style="font-family:Georgia,serif;font-style:italic;font-size:32px;color:#2a1854;letter-spacing:.02em;">Saanguine</div>
          <div style="font-family:'Courier New',monospace;font-size:10px;letter-spacing:.4em;color:#a07e2c;margin-top:6px;">MAISON · MMXXVI</div>
        </td></tr>
        <tr><td style="padding:32px 40px;font-family:Georgia,serif;color:#2a1854;line-height:1.7;">
          ${body}
        </td></tr>
        <tr><td style="padding:24px 40px 32px;border-top:1px solid #e8e0d2;text-align:center;font-family:'Courier New',monospace;font-size:11px;color:#7a6a52;letter-spacing:.1em;">
          Maison Saanguine · Bangladesh<br/>
          <span style="font-size:10px;letter-spacing:.3em;">© MMXXVI · ALL RIGHTS RESERVED</span>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;

export type OrderEmailLine = { name: string; qty: number; lineTotalBdt: number; color?: string | null; size?: string | null };

export type OrderEmailData = {
  number: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  shippingAddress: { line1: string; area?: string; city: string; postcode?: string };
  lines: OrderEmailLine[];
  subtotalBdt: number;
  shippingBdt: number;
  codFeeBdt: number;
  totalBdt: number;
  paymentMethod: "cod" | "card" | "bkash" | "nagad" | "rocket";
  /** Public tracking URL with the per-order token. Generated by the caller. */
  trackingUrl?: string;
};

export function orderPlacedEmail(d: OrderEmailData) {
  const linesHtml = d.lines.map(l => `
    <tr>
      <td style="padding:10px 0;border-bottom:1px solid #f0e8d8;font-family:Georgia,serif;font-size:14px;">
        ${l.name}${l.color ? ` · <span style="color:#7a6a52;font-size:12px;">${l.color}</span>` : ""}${l.size ? ` · <span style="color:#7a6a52;font-size:12px;">${l.size}</span>` : ""}
        <div style="font-family:'Courier New',monospace;font-size:11px;color:#7a6a52;">Qty ${l.qty}</div>
      </td>
      <td style="padding:10px 0;border-bottom:1px solid #f0e8d8;text-align:right;font-family:Georgia,serif;font-size:14px;">${formatBdt(l.lineTotalBdt)}</td>
    </tr>
  `).join("");

  const codNote = d.paymentMethod === "cod"
    ? `<p style="background:#fdf6e8;border:1px solid #e8d8a8;padding:14px 16px;font-size:13px;margin:20px 0 0;">
         <b>Cash on Delivery:</b> please have <b>${formatBdt(d.totalBdt)}</b> ready when our courier arrives.
       </p>`
    : "";

  const subject = `Your maison order ${d.number}`;
  const body = `
    <p style="font-size:15px;margin:0 0 4px;">Dear ${d.customerName.split(" ")[0]},</p>
    <p style="font-size:15px;margin:0 0 24px;">Thank you for your order. The maison has begun the small ceremony of preparing it.</p>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #e8d8a8;">
      <tr><td style="padding:14px 0;font-family:'Courier New',monospace;font-size:11px;letter-spacing:.2em;color:#a07e2c;">ORDER · ${d.number}</td></tr>
    </table>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0">${linesHtml}</table>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:14px;">
      <tr><td style="padding:4px 0;font-size:13px;color:#7a6a52;">Subtotal</td><td style="padding:4px 0;text-align:right;font-size:13px;">${formatBdt(d.subtotalBdt)}</td></tr>
      <tr><td style="padding:4px 0;font-size:13px;color:#7a6a52;">Shipping</td><td style="padding:4px 0;text-align:right;font-size:13px;">${d.shippingBdt === 0 ? "Complimentary" : formatBdt(d.shippingBdt)}</td></tr>
      ${d.codFeeBdt > 0 ? `<tr><td style="padding:4px 0;font-size:13px;color:#7a6a52;">COD handling</td><td style="padding:4px 0;text-align:right;font-size:13px;">${formatBdt(d.codFeeBdt)}</td></tr>` : ""}
      <tr><td style="padding:14px 0 0;border-top:1px solid #e8d8a8;font-family:Georgia,serif;font-size:18px;color:#2a1854;">Total</td><td style="padding:14px 0 0;border-top:1px solid #e8d8a8;text-align:right;font-family:Georgia,serif;font-size:18px;color:#2a1854;font-weight:600;">${formatBdt(d.totalBdt)}</td></tr>
    </table>
    ${codNote}
    <p style="font-family:'Courier New',monospace;font-size:11px;letter-spacing:.2em;color:#a07e2c;margin:32px 0 8px;">DELIVERING TO</p>
    <p style="font-size:14px;line-height:1.6;margin:0;">
      ${d.customerName}<br/>${d.shippingAddress.line1}<br/>${d.shippingAddress.area ? d.shippingAddress.area + ", " : ""}${d.shippingAddress.city}${d.shippingAddress.postcode ? " — " + d.shippingAddress.postcode : ""}<br/>
      ${d.customerPhone}
    </p>
    ${d.trackingUrl ? `<p style="margin:24px 0 0;"><a href="${d.trackingUrl}" style="display:inline-block;background:#2a1854;color:#fdfbf7;text-decoration:none;padding:12px 22px;font-family:Georgia,serif;font-size:14px;letter-spacing:.05em;">Track your order →</a></p>` : ""}
    <p style="font-size:13px;color:#7a6a52;margin:32px 0 0;line-height:1.7;">We will be in touch when the courier collects your parcel. Reply to this email if anything is amiss.</p>
    <p style="font-style:italic;font-size:14px;color:#2a1854;margin:24px 0 0;">— The atelier</p>
  `;
  return { subject, html: SHELL(body) };
}

export function orderShippedEmail(d: OrderEmailData & { courier: string; tracking?: string }) {
  const subject = `On its way · ${d.number}`;
  const body = `
    <p style="font-size:15px;margin:0 0 24px;">Dear ${d.customerName.split(" ")[0]},</p>
    <p style="font-size:15px;margin:0 0 24px;">Your order is in the hands of <b>${d.courier}</b>${d.tracking ? `, tracking <code style="font-family:'Courier New',monospace;background:#f4ecd8;padding:2px 6px;">${d.tracking}</code>` : ""}.</p>
    ${d.paymentMethod === "cod" ? `<p style="background:#fdf6e8;border:1px solid #e8d8a8;padding:14px 16px;font-size:13px;">Please have <b>${formatBdt(d.totalBdt)}</b> ready in cash for the courier.</p>` : ""}
    ${d.trackingUrl ? `<p style="margin:18px 0 0;"><a href="${d.trackingUrl}" style="color:#2a1854;font-weight:500;">View tracking on the maison →</a></p>` : ""}
    <p style="font-style:italic;font-size:14px;color:#2a1854;margin:24px 0 0;">— The atelier</p>
  `;
  return { subject, html: SHELL(body) };
}

// ─── Pre-order request templates ─────────────────────────────────────
export type PreorderEmailData = {
  customerName: string;
  segmentName: string;
  description: string;
  quantity: number;
  budgetHintBdt?: number | null;
  targetDate?: string | null;
  attachmentCount: number;
};

export function preorderReceivedEmail(d: PreorderEmailData) {
  const subject = `We have received your bespoke request · ${d.segmentName}`;
  const body = `
    <p style="font-size:15px;margin:0 0 6px;">Dear ${d.customerName.split(" ")[0] || "friend"},</p>
    <p style="font-size:15px;margin:0 0 24px;">The maison has received your request for a piece in our <em>${d.segmentName}</em> collection. We will look it over carefully and write to you within a day or two with a quote and a proposed timeline.</p>
    <p style="font-family:'Courier New',monospace;font-size:11px;letter-spacing:.2em;color:#a07e2c;margin:0 0 8px;">YOUR REQUEST</p>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #e8d8a8;">
      <tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;width:120px;">Quantity</td><td style="padding:10px 0;font-size:14px;">${d.quantity}</td></tr>
      ${d.budgetHintBdt ? `<tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">Budget hint</td><td style="padding:10px 0;font-size:14px;">${formatBdt(d.budgetHintBdt)}</td></tr>` : ""}
      ${d.targetDate ? `<tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">Hoped-for date</td><td style="padding:10px 0;font-size:14px;">${d.targetDate}</td></tr>` : ""}
      ${d.attachmentCount > 0 ? `<tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">References</td><td style="padding:10px 0;font-size:14px;">${d.attachmentCount} file${d.attachmentCount === 1 ? "" : "s"}</td></tr>` : ""}
    </table>
    <p style="font-family:'Courier New',monospace;font-size:11px;letter-spacing:.2em;color:#a07e2c;margin:24px 0 8px;">YOU WROTE</p>
    <p style="font-size:14px;color:#3a2a64;line-height:1.7;background:#f9f4ec;padding:14px 16px;border-left:2px solid #a07e2c;white-space:pre-wrap;margin:0;">${escapeHtml(d.description)}</p>
    <p style="font-size:13px;color:#7a6a52;margin:32px 0 0;line-height:1.7;">No payment is due now. The maison will write back with a price and timeline; the piece is paid for on delivery.</p>
    <p style="font-style:italic;font-size:14px;color:#2a1854;margin:24px 0 0;">— The atelier</p>
  `;
  return { subject, html: SHELL(body) };
}

export function preorderQuoteEmail(d: PreorderEmailData & { quotedPriceBdt: number; adminNotes?: string | null }) {
  const subject = `A quote for your bespoke piece · ${d.segmentName}`;
  const body = `
    <p style="font-size:15px;margin:0 0 6px;">Dear ${d.customerName.split(" ")[0] || "friend"},</p>
    <p style="font-size:15px;margin:0 0 24px;">We have considered your request and would be honoured to make this for you. The price for the piece, complete and delivered, is:</p>
    <p style="text-align:center;font-family:Georgia,serif;font-size:36px;color:#2a1854;font-weight:400;margin:0 0 24px;">${formatBdt(d.quotedPriceBdt)}</p>
    ${d.adminNotes ? `<p style="font-family:'Courier New',monospace;font-size:11px;letter-spacing:.2em;color:#a07e2c;margin:0 0 8px;">FROM THE ATELIER</p><p style="font-size:14px;color:#3a2a64;line-height:1.7;background:#f9f4ec;padding:14px 16px;border-left:2px solid #a07e2c;white-space:pre-wrap;margin:0 0 24px;">${escapeHtml(d.adminNotes)}</p>` : ""}
    <p style="font-size:13px;color:#7a6a52;margin:0 0 24px;line-height:1.7;">Reply to this email to accept and we will begin. The piece is paid for in cash when our courier arrives at your door — no deposit required.</p>
    <p style="font-style:italic;font-size:14px;color:#2a1854;margin:24px 0 0;">— The atelier</p>
  `;
  return { subject, html: SHELL(body) };
}

export function preorderAdminNotifyEmail(d: PreorderEmailData & {
  requestId: string;
  customerEmail: string;
  customerPhone: string | null;
  adminUrl: string;
}) {
  const subject = `New pre-order request · ${d.segmentName} · ${d.customerName || d.customerEmail}`;
  const body = `
    <p style="font-size:15px;margin:0 0 24px;">A new bespoke request has arrived in <em>${d.segmentName}</em>.</p>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #e8d8a8;">
      <tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;width:140px;">From</td><td style="padding:10px 0;font-size:14px;">${d.customerName || "(no name)"} · ${d.customerEmail}${d.customerPhone ? " · " + d.customerPhone : ""}</td></tr>
      <tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">Quantity</td><td style="padding:10px 0;font-size:14px;">${d.quantity}</td></tr>
      ${d.budgetHintBdt ? `<tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">Budget hint</td><td style="padding:10px 0;font-size:14px;">${formatBdt(d.budgetHintBdt)}</td></tr>` : ""}
      ${d.targetDate ? `<tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">Wants by</td><td style="padding:10px 0;font-size:14px;">${d.targetDate}</td></tr>` : ""}
      <tr><td style="padding:10px 0;font-size:14px;color:#7a6a52;">References</td><td style="padding:10px 0;font-size:14px;">${d.attachmentCount} file${d.attachmentCount === 1 ? "" : "s"}</td></tr>
    </table>
    <p style="font-size:14px;color:#3a2a64;line-height:1.7;background:#f9f4ec;padding:14px 16px;border-left:2px solid #a07e2c;white-space:pre-wrap;margin:24px 0;">${escapeHtml(d.description)}</p>
    <p style="margin:24px 0 0;"><a href="${d.adminUrl}" style="display:inline-block;background:#2a1854;color:#fdfbf7;text-decoration:none;padding:12px 22px;font-family:Georgia,serif;font-size:14px;letter-spacing:.05em;">Open in admin →</a></p>
  `;
  return { subject, html: SHELL(body) };
}

// ─── Newsletter welcome ───────────────────────────────────────────────
export function newsletterWelcomeEmail(siteUrl: string) {
  const subject = "Letters from the Maison — welcome";
  const body = `
    <p style="font-size:15px;margin:0 0 24px;">You asked the maison to write. It will.</p>
    <p style="font-size:15px;margin:0 0 20px;">We send letters rarely — only when there is something genuinely worth pausing for. A new cloth. A scent that took three seasons to settle. A small piece that will not be restocked.</p>
    <p style="font-size:15px;margin:0 0 32px;">The next one will find you when it is ready.</p>
    <p style="margin:0 0 32px;"><a href="${siteUrl}" style="display:inline-block;background:#2a1854;color:#fdfbf7;text-decoration:none;padding:12px 22px;font-family:Georgia,serif;font-size:14px;letter-spacing:.05em;">Wander the boutique &rarr;</a></p>
    <p style="font-style:italic;font-size:14px;color:#2a1854;margin:0;">— The atelier</p>
  `;
  return { subject, html: SHELL(body) };
}

// ─── Review request (sent after order delivered) ──────────────────────
export function reviewRequestEmail(firstName: string, orderNumber: string, trackingUrl: string) {
  const subject = `Your order has arrived · ${orderNumber}`;
  const body = `
    <p style="font-size:15px;margin:0 0 6px;">Dear ${firstName},</p>
    <p style="font-size:15px;margin:0 0 24px;">We hope your parcel arrived in the way the maison intended it — quietly, in the right state.</p>
    <p style="font-size:15px;margin:0 0 24px;">If you have a moment, a few words on the piece would mean a great deal to the small team that prepared it. No obligation. Only if it earned them.</p>
    <p style="margin:0 0 32px;"><a href="${trackingUrl}" style="display:inline-block;background:#2a1854;color:#fdfbf7;text-decoration:none;padding:12px 22px;font-family:Georgia,serif;font-size:14px;letter-spacing:.05em;">Leave a note &rarr;</a></p>
    <p style="font-style:italic;font-size:14px;color:#2a1854;margin:0;">— The atelier</p>
  `;
  return { subject, html: SHELL(body) };
}

// ─── Back in stock ────────────────────────────────────────────────────
export function backInStockEmail(productName: string, productUrl: string) {
  const subject = `Back in the maison · ${productName}`;
  const body = `
    <p style="font-size:11px;letter-spacing:.4em;color:#a07e2c;margin:0 0 14px;font-family:'Courier New',monospace;">BACK ON THE SHELF</p>
    <h2 style="font-size:24px;font-weight:400;color:#2a1854;margin:0 0 14px;font-family:Georgia,serif;">${productName}</h2>
    <p style="font-size:15px;margin:0 0 28px;">The piece you asked the maison to remember has returned. Quantities are limited &mdash; we will not write again until you say so.</p>
    <p style="margin:0 0 6px;"><a href="${productUrl}" style="display:inline-block;background:#2a1854;color:#fdfbf7;text-decoration:none;padding:12px 22px;font-family:Georgia,serif;font-size:14px;letter-spacing:.05em;">Return to the piece &rarr;</a></p>
  `;
  return { subject, html: SHELL(body) };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
